services:
  db:
    image: inventory-manager-postgres
    container_name: inventory-manager-postgres
    environment:
      POSTGRES_PASSWORD: changeme
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: